name = 'material'
source = 'github:muckSponge/MaterialFox'

[[configs]]
key = 'browser.tabs.tabClipWidth'
value = '83'
raw = true

[[configs]]
key = 'security.insecure_connection_text.enabled'
value = 'true'
raw = true
